const PERSONA_AREAS=['Producción','Técnica','Creativo','Marketing','Artístico'];
const MEDIA_CATS = ["Escenario","Camarines","Acceso / Ingreso","Locación general","Otros"];

let PERSONAS=[];
let ASIGNACIONES=[];
let PERFILES_LITE=[];
let editingPersonaId=null;
let eqEditState={};
let NOTAS_CACHE={};

let _photoCache={};
let _mediaActiveCat="todas";
let _lbPhotos=[]; let _lbIdx=0;

// ── LOAD DATA ──
async function loadPersonas(){
  try{ const {data,error}=await sb.from("personas").select("*").order("id",{ascending:true}); if(error){ toast("⚠️ Error cargando equipo: "+error.message); return []; } return (data||[]).map(p=>({id:p.id,nombre:p.nombre||"",cargo:p.cargo||"",area:p.area||"Producción",contacto:p.contacto||"",activo:p.activo!==false,nota:p.nota||"",fotoUrl:p.foto_url||"",perfilId:p.perfil_id||null})); }catch(e){ toast("⚠️ Error de conexión cargando equipo"); return []; } }
async function loadAsignaciones(){
  try{ const {data,error}=await sb.from("asignaciones").select("*"); if(error){ toast("⚠️ Error cargando asignaciones de equipo: "+error.message); return []; } return (data||[]).map(a=>({id:a.id,entityType:a.entity_type,entityId:a.entity_id,personaId:a.persona_id,rol:a.rol_contexto||"",tarea:a.tarea||"",viaja:!!a.viaja,estado:a.estado||"confirmado"})); }catch(e){ toast("⚠️ Error de conexión cargando asignaciones de equipo"); return []; } }
async function loadPerfilesLite(){ try{ const {data,error}=await sb.from("perfiles").select("id,nombre,avatar_url,email"); if(error)return []; return (data||[]).map(p=>({id:p.id,nombre:p.nombre||"",avatarUrl:p.avatar_url||"",email:(p.email||"").toLowerCase()})); }catch(e){ return []; } }

// ── PERSONAS ──
function personaAvatarSrc(p){
  if(p.fotoUrl)return p.fotoUrl;
  if(p.perfilId){ const perfil=PERFILES_LITE.find(x=>String(x.id)===String(p.perfilId)); if(perfil&&perfil.avatarUrl)return perfil.avatarUrl; }
  return null;
}
function personaAvatarHTML(p,cls){
  const letter=(p.nombre||"?").charAt(0).toUpperCase();
  const src=personaAvatarSrc(p);
  if(src)return `<div class="${cls}"><img src="${src}" alt="" onerror="this.outerHTML='${letter}'"></div>`;
  return `<div class="${cls}">${letter}</div>`;
}
function populatePerfilSelect(selectedId){
  const sel=document.getElementById("per-f-perfil"); if(!sel)return;
  sel.innerHTML='<option value="">— Ninguno —</option>'+PERFILES_LITE.map(pf=>`<option value="${pf.id}" ${String(pf.id)===String(selectedId)?"selected":""}>${pf.nombre}</option>`).join("");
}
function matchPerfilByEmail(contactoRaw){ const v=(contactoRaw||"").trim().toLowerCase(); if(!v||!v.includes("@"))return null; return PERFILES_LITE.find(pf=>pf.email&&pf.email===v)||null; }
function autoMatchPerfilByContacto(){ const sel=document.getElementById("per-f-perfil"); if(!sel||sel.value)return; const match=matchPerfilByEmail(document.getElementById("per-f-contacto").value); if(match){ populatePerfilSelect(match.id); toast("🔗 Vinculado automáticamente a "+match.nombre+" (por email)"); } }

function showAddPersonaForm(){ editingPersonaId=null; document.getElementById("persona-add-area").style.display="block"; ["per-f-nombre","per-f-cargo","per-f-contacto","per-f-foto"].forEach(id=>{const el=document.getElementById(id);if(el)el.value="";}); document.getElementById("per-f-area").value="Producción"; populatePerfilSelect(null); }
function hideAddPersonaForm(){ document.getElementById("persona-add-area").style.display="none"; editingPersonaId=null; }
function editPersona(id){ const p=PERSONAS.find(x=>x.id===id); if(!p)return; editingPersonaId=id; document.getElementById("persona-add-area").style.display="block"; document.getElementById("per-f-nombre").value=p.nombre; document.getElementById("per-f-cargo").value=p.cargo; document.getElementById("per-f-area").value=p.area; document.getElementById("per-f-contacto").value=p.contacto; document.getElementById("per-f-foto").value=p.fotoUrl||""; if(!p.perfilId){ const match=matchPerfilByEmail(p.contacto); populatePerfilSelect(match?match.id:null); } else { populatePerfilSelect(p.perfilId); } }
async function savePersona(){ const nombre=document.getElementById("per-f-nombre").value.trim(); if(!nombre){toast("⚠️ Ingresá un nombre.");return;} const cargo=document.getElementById("per-f-cargo").value.trim(); const area=document.getElementById("per-f-area").value; const contacto=document.getElementById("per-f-contacto").value.trim(); const fotoUrl=document.getElementById("per-f-foto").value.trim(); let perfilIdRaw=document.getElementById("per-f-perfil").value; if(!perfilIdRaw){ const match=matchPerfilByEmail(contacto); if(match)perfilIdRaw=String(match.id); } const payload={nombre,cargo,area,contacto,foto_url:fotoUrl||null,perfil_id:perfilIdRaw||null}; try{ if(editingPersonaId!=null){ const {error}=await sb.from("personas").update(payload).eq("id",editingPersonaId); if(error){toast("⚠️ Error guardando: "+error.message);return;} const idx=PERSONAS.findIndex(p=>p.id===editingPersonaId); if(idx>=0)PERSONAS[idx]={...PERSONAS[idx],nombre,cargo,area,contacto,fotoUrl,perfilId:perfilIdRaw||null}; toast("✅ Persona actualizada"); } else { const {data,error}=await sb.from("personas").insert({...payload,activo:true}).select().single(); if(error){toast("⚠️ Error guardando: "+error.message);return;} PERSONAS.push({id:data.id,nombre:data.nombre,cargo:data.cargo||"",area:data.area,contacto:data.contacto||"",fotoUrl:data.foto_url||"",perfilId:data.perfil_id||null,activo:true,nota:""}); toast("✅ Persona agregada"); } }catch(e){toast("⚠️ Error de conexión guardando persona");return;} hideAddPersonaForm(); buildEquipo(); }
async function togglePersonaActivo(id){ const p=PERSONAS.find(x=>x.id===id); if(!p)return; const nuevoActivo=!p.activo; try{ const {error}=await sb.from("personas").update({activo:nuevoActivo}).eq("id",id); if(error){toast("⚠️ Error actualizando: "+error.message);return;} p.activo=nuevoActivo; toast(nuevoActivo?"✅ Marcada como activa":"💤 Marcada como inactiva"); }catch(e){toast("⚠️ Error de conexión");return;} buildEquipo(); }
async function deletePersona(id){ const p=PERSONAS.find(x=>x.id===id); if(!p)return; if(!confirm("¿Eliminar a "+p.nombre+" del equipo? También se quitará de cualquier show/contenido donde esté asignada, y sus notas."))return; try{ const {error}=await sb.from("personas").delete().eq("id",id); if(error){toast("⚠️ Error eliminando: "+error.message);return;} PERSONAS=PERSONAS.filter(x=>x.id!==id); ASIGNACIONES=ASIGNACIONES.filter(a=>a.personaId!==id); sb.from("notas_equipo").delete().eq("entity_type","persona").eq("entity_id",id).then(()=>{}); delete NOTAS_CACHE[eqKey("persona",id)]; toast("🗑 Persona eliminada"); }catch(e){toast("⚠️ Error de conexión eliminando persona");return;} buildEquipo(); renderFullDetailIfOpen(); }

// ── EQUIPO BUILD ──
function buildEquipo(){
  const canEdit=currentUser&&ROLE_DEFS[currentUser.rol]?.canEdit;
  const addBtn=document.getElementById("persona-add-btn"); if(addBtn)addBtn.style.display=canEdit?"flex":"none";
  const grid=document.getElementById("personas-grid"); if(!grid)return;
  if(!PERSONAS.length){ grid.innerHTML="<div style='font-size:11px;color:#aaa;'>Todavía no hay personas registradas. "+(canEdit?"Usá '+ Agregar persona'.":"")+"</div>"; return; }
  const activos=PERSONAS.filter(p=>p.activo); const inactivos=PERSONAS.filter(p=>!p.activo);
  grid.innerHTML=[...activos,...inactivos].map(p=>{ const upcoming=personaUpcomingAsignaciones(p.id); return `<div><div class="team-card ${p.activo?"":"inactivo"}">${personaAvatarHTML(p,"team-av")}<div class="ti" style="flex:1;"><div class="tn">${p.nombre}${p.activo?"":" <span style='font-size:9px;color:#bbb;'>(inactiva)</span>"}</div><div class="tr">${p.cargo||"—"}</div><div class="ta">${p.area}${p.contacto?" · "+p.contacto:""}</div></div><div style="display:flex;flex-direction:column;gap:4px;align-items:flex-end;"><button class="btn" style="font-size:9px;padding:2px 7px;white-space:nowrap;" onclick="togglePersonaExtra(${p.id})">📅 ${upcoming.length} próx. · 💬 bitácora</button>${canEdit?`<div style="display:flex;gap:4px;"><button class="btn" style="font-size:9px;padding:2px 7px;" onclick="editPersona(${p.id})">Editar</button><button class="btn" style="font-size:9px;padding:2px 7px;" onclick="togglePersonaActivo(${p.id})">${p.activo?"Desactivar":"Activar"}</button><button class="btn" style="font-size:9px;padding:2px 7px;color:var(--r600);border-color:var(--r100);" onclick="deletePersona(${p.id})">Eliminar</button></div>`:""}</div></div><div id="persona-extra-${p.id}" style="display:none;"></div></div>`; }).join("");
}

function personaUpcomingAsignaciones(personaId){ const today=new Date();today.setHours(0,0,0,0); return ASIGNACIONES.filter(a=>a.personaId===personaId&&a.entityType==="show").map(a=>({a,show:SHOWS.find(s=>String(s.id)===String(a.entityId))})).filter(x=>x.show&&x.show.fecha&&new Date(x.show.fecha)>=today).sort((x,y)=>new Date(x.show.fecha)-new Date(y.show.fecha)); }
function togglePersonaExtra(id){ const el=document.getElementById("persona-extra-"+id); if(!el)return; const open=el.style.display!=="none"&&el.style.display!==""; if(open){el.style.display="none";return;} el.style.display="block"; renderPersonaExtra(id); }
function renderPersonaExtra(id){ const el=document.getElementById("persona-extra-"+id); if(!el)return; const upcoming=personaUpcomingAsignaciones(id); const agendaHTML=upcoming.length?upcoming.map(({a,show})=>`<div style="display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-bottom:0.5px solid var(--border-soft);font-size:11px;"><span>${fmtDate(show.fecha)} · ${show.nombre}${a.rol?" ("+a.rol+")":""}</span>${a.viaja?'<span title="Viaja">✈️</span>':""}</div>`).join(""):"<div style='font-size:11px;color:#aaa;'>Sin shows próximos asignados.</div>"; el.innerHTML=`<div class="card" style="margin-top:6px;"><h3 style="font-size:11px;">📅 Próximos shows</h3><div style="margin-top:6px;">${agendaHTML}</div></div>${notasHTML("persona",id)}`; }

// ── ASIGNACIONES ──
function eqKey(entityType,entityId){return entityType+":"+entityId;}
function getAsignaciones(entityType,entityId){ return ASIGNACIONES.filter(a=>a.entityType===entityType&&String(a.entityId)===String(entityId)); }
function equipoStackHTML(entityType,entityId,max){
  const asign=getAsignaciones(entityType,entityId); const personasAsig=asign.map(a=>PERSONAS.find(p=>p.id===a.personaId)).filter(Boolean);
  if(!personasAsig.length)return '<span style="font-size:10px;color:#bbb;">—</span>';
  const shown=personasAsig.slice(0,max); const extra=personasAsig.length-shown.length;
  const avs=shown.map(p=>personaAvatarHTML(p,"eq-av-mini")).join("");
  const extraHTML=extra>0?`<div class="eq-av-mini" style="background:#eee;color:#999;">+${extra}</div>`:"";
  const title=personasAsig.map(p=>p.nombre).join(", ").replace(/"/g,"&quot;");
  return `<div class="eq-stack" title="${title}">${avs}${extraHTML}</div>`;
}
function equipoAsignadoHTML(entityType,entityId,canEdit){
  const key=eqKey(entityType,entityId);
  if(!eqEditState[key]){ eqEditState[key]=getAsignaciones(entityType,entityId).map(a=>({personaId:a.personaId,rol:a.rol,tarea:a.tarea,viaja:a.viaja})); }
  const sel=eqEditState[key]; const activos=PERSONAS.filter(p=>p.activo);
  if(!activos.length){ return `<div class="card"><h3>Equipo asignado</h3><p style="font-size:11px;color:#aaa;margin-top:8px;">No hay personas activas registradas en Equipo todavía.</p></div>`; }
  const chips=activos.map(p=>{ const isSel=sel.some(s=>s.personaId===p.id); return `<div class="eq-chip ${isSel?"selected":""}" ${canEdit?`onclick="toggleEquipoPersona('${entityType}',${entityId},${p.id})"`:""}>${p.nombre}</div>`; }).join("");
  const rows=sel.map(s=>{ const p=PERSONAS.find(x=>x.id===s.personaId); if(!p)return""; return `<div class="eq-row"><input type="text" ${canEdit?"":"disabled"} placeholder="Rol en este contexto (ej: Sonidista)" value="${s.rol||""}" onchange="updateEquipoField('${entityType}',${entityId},${p.id},'rol',this.value)"><input type="text" ${canEdit?"":"disabled"} placeholder="Tarea / nota (opcional)" value="${s.tarea||""}" onchange="updateEquipoField('${entityType}',${entityId},${p.id},'tarea',this.value)"><label><input type="checkbox" ${s.viaja?"checked":""} ${canEdit?"":"disabled"} onchange="updateEquipoField('${entityType}',${entityId},${p.id},'viaja',this.checked)"> ✈️ Viaja</label></div>`; }).join("");
  return `<div class="card"><h3>Equipo asignado</h3><div style="font-size:11px;color:#888;margin:6px 0 10px;">${canEdit?"Tocá una persona para sumarla o sacarla del equipo de este show/contenido.":"Personas asignadas a este show/contenido."}</div><div style="display:flex;flex-wrap:wrap;gap:6px;">${chips}</div>${rows?`<div style="margin-top:10px;">${rows}</div>`:""}${canEdit?`<div style="margin-top:12px;"><button class="btn btn-primary" style="font-size:11px;" onclick="saveEquipoAsignado('${entityType}',${entityId})">Guardar equipo</button></div>`:""}</div>`;
}
function toggleEquipoPersona(entityType,entityId,personaId){ const key=eqKey(entityType,entityId); const sel=eqEditState[key]||[]; const idx=sel.findIndex(s=>s.personaId===personaId); if(idx>=0)sel.splice(idx,1); else sel.push({personaId,rol:"",tarea:"",viaja:false}); eqEditState[key]=sel; rerenderEquipoAsignado(entityType,entityId); }
function updateEquipoField(entityType,entityId,personaId,field,value){ const key=eqKey(entityType,entityId); const sel=eqEditState[key]||[]; const item=sel.find(s=>s.personaId===personaId); if(item)item[field]=value; }
function rerenderEquipoAsignado(entityType,entityId){ if(entityType!=="show")return; if(fullDetailIdx!==null&&fullDetailActiveTab==="equipo"&&String(SHOWS[fullDetailIdx]?.id)===String(entityId)){ renderFullDetailIfOpen(); } const panelOpen=document.getElementById("panel-overlay")?.classList.contains("open"); if(panelOpen&&panelActiveTab==="equipo"&&activeShowIdx!=null&&String(SHOWS[activeShowIdx]?.id)===String(entityId)){ panelTab("equipo",activeShowIdx); } }
async function persistAsignaciones(entityType,entityId,items){
  try{ const {error:delErr}=await sb.from("asignaciones").delete().eq("entity_type",entityType).eq("entity_id",entityId); if(delErr){toast("⚠️ Error actualizando equipo: "+delErr.message);return false;} ASIGNACIONES=ASIGNACIONES.filter(a=>!(a.entityType===entityType&&String(a.entityId)===String(entityId))); if(items.length){ const payload=items.map(it=>({entity_type:entityType,entity_id:entityId,persona_id:it.personaId,rol_contexto:it.rol||"",tarea:it.tarea||"",viaja:!!it.viaja,estado:"confirmado"})); const {data:inserted,error:insErr}=await sb.from("asignaciones").insert(payload).select(); if(insErr){toast("⚠️ Error guardando equipo: "+insErr.message);return false;} (inserted||[]).forEach(row=>{ ASIGNACIONES.push({id:row.id,entityType:row.entity_type,entityId:row.entity_id,personaId:row.persona_id,rol:row.rol_contexto||"",tarea:row.tarea||"",viaja:!!row.viaja,estado:row.estado}); }); } return true; }catch(e){toast("⚠️ Error de conexión guardando equipo");return false;} }
async function saveEquipoAsignado(entityType,entityId){ const key=eqKey(entityType,entityId); const items=eqEditState[key]||[]; const ok=await persistAsignaciones(entityType,entityId,items); if(!ok)return; toast("✅ Equipo actualizado"); delete eqEditState[key]; rerenderEquipoAsignado(entityType,entityId); buildEquipo(); }

// ── NOTAS ──
function notasContainerId(entityType,entityId){return "notas-c-"+entityType+"-"+entityId;}
function notasHTML(entityType,entityId){ const key=eqKey(entityType,entityId); const cid=notasContainerId(entityType,entityId); if(!NOTAS_CACHE[key]){ NOTAS_CACHE[key]="loading"; fetchNotas(entityType,entityId); } return `<div class="card" style="max-width:680px;"><h3>💬 Bitácora</h3><div id="${cid}" style="margin-top:8px;">${renderNotasInner(entityType,entityId)}</div></div>`; }
async function fetchNotas(entityType,entityId){ const key=eqKey(entityType,entityId); try{ const {data,error}=await sb.from("notas_equipo").select("*").eq("entity_type",entityType).eq("entity_id",entityId).order("id",{ascending:true}); if(error){toast("⚠️ Error cargando bitácora: "+error.message);NOTAS_CACHE[key]=[];} else NOTAS_CACHE[key]=(data||[]).map(n=>({id:n.id,autor:n.autor||"",texto:n.texto||"",createdAt:n.created_at})); }catch(e){NOTAS_CACHE[key]=[];} const el=document.getElementById(notasContainerId(entityType,entityId)); if(el)el.innerHTML=renderNotasInner(entityType,entityId); }
function renderNotasInner(entityType,entityId){ const key=eqKey(entityType,entityId); const list=NOTAS_CACHE[key]; const canDelete=currentUser&&ROLE_DEFS[currentUser.rol]?.canEdit; let entries; if(list==="loading"||list===undefined)entries="<div style='color:#666;font-size:13px;padding:16px 0;'>Cargando…</div>"; else if(!list.length)entries="<div style='color:#666;font-size:13px;padding:16px 0;'>No hay entradas en la bitácora todavía.</div>"; else entries=list.map(n=>`<div class="cd-log-entry"><div class="cd-log-meta"><span style="font-weight:700;color:#B7B2DA;">${(n.autor||"—").replace(/</g,"&lt;")}</span><span>${n.createdAt?new Date(n.createdAt).toLocaleString("es-CL",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):""}</span>${canDelete?`<button onclick="deleteNota('${entityType}',${entityId},${n.id})" style="background:none;border:none;cursor:pointer;color:#666;font-size:11px;margin-left:auto;padding:0;">✕ eliminar</button>`:""}</div><div class="cd-log-texto">${(n.texto||"").replace(/</g,"&lt;")}</div></div>`).join("");
  return `<div class="cd-log-thread">${entries}</div><div class="cd-log-input-row"><textarea id="nota-input-${entityType}-${entityId}" placeholder="Anotá una actualización, decisión, comentario..."></textarea><button class="btn btn-primary" style="font-size:12px;white-space:nowrap;align-self:flex-end;" onclick="addNota('${entityType}',${entityId})">Agregar ↵</button></div><p style="font-size:10px;color:#666;margin-top:8px;">Las entradas se registran con tu nombre (${(currentUser?.nombre||"—").replace(/</g,"&lt;")}) y la fecha/hora actual.</p>`; }
async function addNota(entityType,entityId){ const input=document.getElementById("nota-input-"+entityType+"-"+entityId); const texto=input?input.value.trim():""; if(!texto)return; const autor=currentUser?currentUser.nombre:"—"; try{ const {data,error}=await sb.from("notas_equipo").insert({entity_type:entityType,entity_id:entityId,autor,texto}).select().single(); if(error){toast("⚠️ Error guardando nota: "+error.message);return;} const key=eqKey(entityType,entityId); if(!Array.isArray(NOTAS_CACHE[key]))NOTAS_CACHE[key]=[]; NOTAS_CACHE[key].push({id:data.id,autor:data.autor,texto:data.texto,createdAt:data.created_at}); if(input)input.value=""; const el=document.getElementById(notasContainerId(entityType,entityId)); if(el)el.innerHTML=renderNotasInner(entityType,entityId); }catch(e){toast("⚠️ Error de conexión guardando nota");} }
async function deleteNota(entityType,entityId,notaId){ if(!confirm("¿Eliminar esta nota?"))return; try{ const {error}=await sb.from("notas_equipo").delete().eq("id",notaId); if(error){toast("⚠️ Error eliminando: "+error.message);return;} const key=eqKey(entityType,entityId); if(Array.isArray(NOTAS_CACHE[key]))NOTAS_CACHE[key]=NOTAS_CACHE[key].filter(n=>n.id!==notaId); const el=document.getElementById(notasContainerId(entityType,entityId)); if(el)el.innerHTML=renderNotasInner(entityType,entityId); }catch(e){toast("⚠️ Error de conexión eliminando nota");} }

// ── MULTIMEDIA ──
async function loadPhotos(showIdx){
  if(_photoCache[showIdx])return _photoCache[showIdx];
  const show=SHOWS[showIdx]; if(!show||!show.id)return[];
  try{ const {data,error}=await sb.from("media_items").select("*").eq("show_id",show.id).order("created_at",{ascending:true}); if(error){ toast("⚠️ Error cargando fotos: "+error.message); return[]; } const photos=(data||[]).map(row=>({id:String(row.id),cat:row.categoria||"Otros",label:row.label||"",src:row.url,tipo:row.tipo||"file",storagePath:row.storage_path||null,ts:row.created_at||""})); _photoCache[showIdx]=photos; return photos; }catch(e){ toast("⚠️ Error de conexión cargando fotos"); return[]; } }
function invalidatePhotoCache(showIdx){ delete _photoCache[showIdx]; }
async function savePhotoFile(showIdx, file, cat, label){
  const show=SHOWS[showIdx]; if(!show||!show.id){ toast("⚠️ Show sin id, guardá el show primero"); return null; }
  const ext=file.name.split('.').pop()||'jpg'; const path=`shows/${show.id}/${Date.now()}_${Math.random().toString(36).slice(2,6)}.${ext}`;
  try{ const {error:upErr}=await sb.storage.from(STORAGE_BUCKET).upload(path, file, {contentType:file.type,upsert:false}); if(upErr){ toast("⚠️ Error subiendo foto: "+upErr.message); return null; } const {data:urlData}=sb.storage.from(STORAGE_BUCKET).getPublicUrl(path); const {data:row,error:insErr}=await sb.from("media_items").insert({show_id:show.id,categoria:cat||"Otros",label:label||file.name.replace(/\.[^.]+$/,""),url:urlData.publicUrl,storage_path:path,tipo:"file"}).select().single(); if(insErr){ toast("⚠️ Error guardando metadata: "+insErr.message); return null; } const photo={id:String(row.id),cat:row.categoria||"Otros",label:row.label||"",src:row.url,tipo:"file",storagePath:path,ts:row.created_at||""}; invalidatePhotoCache(showIdx); return photo; }catch(e){ toast("⚠️ Error de conexión subiendo foto"); return null; } }
async function savePhotoUrl(showIdx, url, cat){
  const show=SHOWS[showIdx]; if(!show||!show.id){ toast("⚠️ Show sin id"); return null; }
  try{ const {data:row,error}=await sb.from("media_items").insert({show_id:show.id,categoria:cat||"Otros",label:url.split("/").pop().split("?")[0]||"Imagen URL",url:url,storage_path:null,tipo:"url"}).select().single(); if(error){ toast("⚠️ Error guardando URL: "+error.message); return null; } const photo={id:String(row.id),cat:row.categoria||"Otros",label:row.label||"",src:row.url,tipo:"url",storagePath:null,ts:row.created_at||""}; invalidatePhotoCache(showIdx); return photo; }catch(e){ toast("⚠️ Error de conexión guardando URL"); return null; } }
async function deletePhoto(showIdx, photoId){
  try{ const photos=_photoCache[showIdx]||[]; const photo=photos.find(p=>p.id===String(photoId)); if(photo&&photo.storagePath){ const {error:stErr}=await sb.storage.from(STORAGE_BUCKET).remove([photo.storagePath]); if(stErr)console.warn("No se pudo borrar del bucket:",stErr.message); } const {error}=await sb.from("media_items").delete().eq("id",photoId); if(error){ toast("⚠️ Error borrando foto: "+error.message); return false; } invalidatePhotoCache(showIdx); return true; }catch(e){ toast("⚠️ Error de conexión borrando foto"); return false; } }
async function updatePhotoCategory(showIdx, photoId, newCat){
  try{ const {data,error}=await sb.from("media_items").update({categoria:newCat}).eq("id",photoId).select(); if(error){ toast("⚠️ Error actualizando categoría: "+error.message); return false; } if(!data||data.length===0){ toast("⚠️ No se actualizó ninguna fila — revisá los permisos (RLS) de UPDATE en media_items"); return false; } invalidatePhotoCache(showIdx); return true; }catch(e){ toast("⚠️ Error de conexión actualizando categoría"); return false; } }
async function changePhotoCat(showIdx, photoId, newCat, pref){ const ok=await updatePhotoCategory(showIdx, photoId, newCat); if(ok){ await renderMediaGrid(showIdx, pref); toast("✅ Categoría actualizada → "+newCat); } }

function multimediaHTML(s,showIdx,isPanel){
  const canUpload=currentUser&&ROLE_DEFS[currentUser.rol]?.canEdit;
  const pref=isPanel?"pnl":"fd";
  const cachedPhotos=_photoCache[showIdx]; const cnt=cachedPhotos?cachedPhotos.length:0;
  return`<div id="${pref}-media-wrap" style="${isPanel?"":"max-width:900px;"}">
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;flex-wrap:wrap;gap:8px;">
      <div><span style="font-size:13px;font-weight:700;color:#F5F4FB;">Fotos de locación</span><span class="media-counter" id="${pref}-media-cnt">${cnt} foto${cnt!==1?"s":""}</span></div>
      ${canUpload?`<div style="display:flex;gap:7px;align-items:center;"><select id="${pref}-upload-cat" style="font-size:11px;padding:5px 8px;border-radius:6px;border:0.5px solid var(--border-soft);background:var(--surface);color:#E4E1F7;">${MEDIA_CATS.map(c=>`<option value="${c}">${c}</option>`).join("")}</select><button class="btn" style="font-size:11px;" onclick="document.getElementById('${pref}-file-input').click()">📁 Subir foto(s)</button><input type="file" id="${pref}-file-input" accept="image/*" multiple style="display:none;" onchange="handleFileUpload(event,${showIdx},'${pref}')"></div>`:""}
    </div>
    ${canUpload?`<div style="margin-bottom:14px;"><div class="media-url-row"><input type="url" id="${pref}-url-input" placeholder="O pegá una URL de imagen (https://...)" style="font-size:12px;"><select id="${pref}-url-cat" style="min-width:140px;">${MEDIA_CATS.map(c=>`<option value="${c}">${c}</option>`).join("")}</select><button class="btn btn-primary" style="font-size:11px;white-space:nowrap;" onclick="addPhotoUrl(${showIdx},'${pref}')">Agregar URL</button></div><div class="media-upload-zone" id="${pref}-drop-zone" ondragover="event.preventDefault();this.classList.add('drag-over')" ondragleave="this.classList.remove('drag-over')" ondrop="handleDrop(event,${showIdx},'${pref}')"><div class="muz-icon">🖼️</div><div class="muz-label">Arrastrá fotos aquí, o usá el botón de arriba</div><div class="muz-sub">JPG, PNG, WEBP · Hasta 20 MB por foto</div></div></div>`:""}
    <div class="media-cat-tabs" id="${pref}-cat-tabs"><button class="media-cat-tab active" onclick="filterMediaCat('todas',${showIdx},'${pref}')">Todas</button>${MEDIA_CATS.map(c=>`<button class="media-cat-tab" onclick="filterMediaCat('${c}',${showIdx},'${pref}')">${c}</button>`).join("")}</div>
    <div class="media-grid${isPanel?"":" large"}" id="${pref}-media-grid"></div>
  </div>`;
}
function initMultimediaZone(showIdx, isPanel){ _mediaActiveCat="todas"; renderMediaGrid(showIdx, isPanel?"pnl":"fd"); }
async function renderMediaGrid(showIdx, pref){
  const grid=document.getElementById(pref+"-media-grid"); const cntEl=document.getElementById(pref+"-media-cnt"); if(!grid)return;
  grid.innerHTML=`<div class="media-empty" style="grid-column:1/-1;color:#666;">Cargando fotos...</div>`;
  const photos=await loadPhotos(showIdx); const canUpload=currentUser&&ROLE_DEFS[currentUser.rol]?.canEdit;
  const filtered=_mediaActiveCat==="todas"?photos:photos.filter(p=>p.cat===_mediaActiveCat);
  if(cntEl){ const n=photos.length; cntEl.textContent=n+" foto"+(n!==1?"s":""); }
  MEDIA_CATS.forEach(c=>{ const btns=document.querySelectorAll(`#${pref}-cat-tabs .media-cat-tab`); btns.forEach(b=>{ if(b.textContent.replace(/\s*\(\d+\)/,"")===c){ const n=photos.filter(p=>p.cat===c).length; b.textContent=c+(n>0?` (${n})`:``); } }); });
  if(!filtered.length){ grid.innerHTML=`<div class="media-empty" style="grid-column:1/-1;">${_mediaActiveCat==="todas"?"Todavía no hay fotos cargadas para este show.":"No hay fotos en esta categoría."}</div>`; return; }
  _lbPhotos=filtered;
  grid.innerHTML=filtered.map((p,i)=>`<div class="media-thumb" onclick="openLightbox(${i})"><img src="${p.src}" alt="${p.label||""}" loading="lazy">${canUpload?`<select class="media-cat-badge media-cat-badge-sel" onclick="event.stopPropagation()" onchange="event.stopPropagation();changePhotoCat(${showIdx},'${p.id}',this.value,'${pref}')">${MEDIA_CATS.map(c=>`<option value="${c}" ${c===(p.cat||"Otros")?"selected":""}>${c}</option>`).join("")}</select>`:`<div class="media-cat-badge">${p.cat||"Otros"}</div>`}<div class="media-thumb-overlay"><div class="media-thumb-label">${p.label||p.cat||""}</div></div>${canUpload?`<button class="media-thumb-del" onclick="event.stopPropagation();confirmDeletePhoto(${showIdx},'${p.id}','${pref}')" title="Eliminar">✕</button>`:""}</div>`).join("");
}
function filterMediaCat(cat, showIdx, pref){ _mediaActiveCat=cat; document.querySelectorAll(`#${pref}-cat-tabs .media-cat-tab`).forEach(b=>{ b.classList.toggle("active", b.textContent.replace(/\s*\(\d+\)/,"")===cat || (cat==="todas" && b.textContent==="Todas")); }); renderMediaGrid(showIdx,pref); }
function handleFileUpload(e, showIdx, pref){ const files=Array.from(e.target.files); e.target.value=""; if(!files.length)return; processFiles(files, showIdx, pref); }
function handleDrop(e, showIdx, pref){ e.preventDefault(); document.getElementById(pref+"-drop-zone")?.classList.remove("drag-over"); const files=Array.from(e.dataTransfer.files).filter(f=>f.type.startsWith("image/")); if(!files.length){toast("⚠️ Solo se aceptan archivos de imagen.");return;} processFiles(files, showIdx, pref); }
async function processFiles(files, showIdx, pref){ const errors=[]; const validFiles=files.filter(file=>{ if(file.size>MAX_PHOTO_BYTES){ errors.push(file.name+" (supera 49 MB)"); return false; } return true; }); if(errors.length)toast("⚠️ Archivos omitidos: "+errors.join(", ")); if(!validFiles.length)return; const catSel=document.getElementById(pref+'-upload-cat'); const cat=catSel?catSel.value:MEDIA_CATS[0]; toast("⏳ Subiendo "+validFiles.length+" foto"+(validFiles.length!==1?"s":"")+" a \""+cat+"\"..."); const uploadErrors=[]; for(const file of validFiles){ const result=await savePhotoFile(showIdx, file, cat, file.name.replace(/\.[^.]+$/,"")); if(!result)uploadErrors.push(file.name); } await renderMediaGrid(showIdx, pref); if(uploadErrors.length) toast("⚠️ No se pudieron subir: "+uploadErrors.join(", ")); else toast("✅ "+validFiles.length+" foto"+(validFiles.length!==1?"s":"")+" subida"+(validFiles.length!==1?"s":"")); }
async function addPhotoUrl(showIdx, pref){ const input=document.getElementById(pref+"-url-input"); const catSel=document.getElementById(pref+"-url-cat"); const url=input?.value.trim(); const cat=catSel?.value||"Otros"; if(!url||!url.startsWith("http")){toast("⚠️ Ingresá una URL válida (https://...)");return;} const result=await savePhotoUrl(showIdx, url, cat); if(result){ if(input)input.value=""; await renderMediaGrid(showIdx,pref); toast("✅ Foto URL agregada"); } }
async function confirmDeletePhoto(showIdx, photoId, pref){ if(!confirm("¿Eliminar esta foto?"))return; const ok=await deletePhoto(showIdx,photoId); if(ok){ await renderMediaGrid(showIdx,pref); toast("🗑 Foto eliminada"); } }

// ── LIGHTBOX ──
function openLightbox(idx){ _lbIdx=idx; const p=_lbPhotos[idx]; if(!p)return; const lb=document.getElementById("media-lightbox"); document.getElementById("lb-img").src=p.src; document.getElementById("lb-caption").textContent=(p.label||"")+(_lbPhotos.length>1?" · "+(idx+1)+" / "+_lbPhotos.length:"")+" · "+p.cat; lb.classList.add("open"); document.body.style.overflow="hidden"; }
function closeLightbox(e){ if(e&&e.target!==document.getElementById("media-lightbox")&&e.target.tagName!=="DIV")return; document.getElementById("media-lightbox").classList.remove("open"); document.getElementById("lb-img").src=""; document.body.style.overflow=""; }
function lbNav(dir){ const next=(_lbIdx+dir+_lbPhotos.length)%_lbPhotos.length; openLightbox(next); }
document.addEventListener("keydown",e=>{ const lb=document.getElementById("media-lightbox"); if(!lb.classList.contains("open"))return; if(e.key==="Escape")closeLightbox({target:lb}); if(e.key==="ArrowRight")lbNav(1); if(e.key==="ArrowLeft")lbNav(-1); });